main: cn.wode490390.nukkit.eventscontroller.EventsController
name: "EventsController"
author: "wode490390"
description: "Events controller plugin for Nukkit"
website: "http://wode490390.cn/"
version: "${pom.version}"
api: ["1.0.0"]
load: POSTWORLD
